spring.application.name=Tour-Management
server.port=9090


spring.datasource.url=jdbc:postgresql://localhost:1000/tour-management
spring.datasource.username=panha
spring.datasource.password=panha


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
logging.level.org.hibernate.orm.jdbc.bind=TRACE
